name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build and Test
        run: |
          ./gradlew build
          ./gradlew AggregateJacocoReport
          mv build/reports/jacoco/aggregate/html ./coverage
          mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
          echo `cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./coverage

      - name: Publish Code Coverage
        uses: codecov/codecov-action@v2
        with:
          flags: unittests
